---
name: "Linting"

on:
  push:

# Disable all default permissions
permissions: {}

jobs:
  go:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod

      - name: go mod tidy
        run: go mod tidy -diff

      - name: go test
        run: go test -v ./...

  golangci-lint:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
        with:
          # renovate: datasource=github-releases depName=golangci/golangci-lint
          version: v2.0.2
